{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apexdata-agent.fullname" . }}-otel-collector-credentials
  namespace: {{ include "apexdata-agent.namespace" . }}
  labels:
    {{- include "apexdata-agent.otelCollector.labels" . | nindent 4 }}
type: Opaque
stringData:
  OTEL_REMOTE_ENDPOINT: {{ include "apexdata-agent.otelEndpoint" . | quote }}
  OTEL_AUTH_HEADER: "Basic {{ printf "%s:%s" .Values.apexdata.clientName .Values.apexdata.password | b64enc }}"
{{- end }}
