apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apexdata-agent.fullname" . }}-otlp-credentials
  namespace: {{ include "apexdata-agent.namespace" . }}
  labels:
    {{- include "apexdata-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ include "apexdata-agent.otelEndpoint" . | quote }}
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic {{ printf "%s:%s" .Values.apexdata.clientName .Values.apexdata.password | b64enc }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
